sudo: required 
language: node_js
node_js:
    - 17
    
services: 
    - docker
before_install: 
    - docker build -t sample-app -f Dockerfile.dev .
script:     
    - docker run -e CI=true sample-app npm run test -- --coverage --watchAll=false